[tool.poetry]
name = "test-runner"
version = "0.0.0"
description = "Run tests from the circom benchmarks"
authors = ["Sepanski <ben.sepanski@veridise.com>"]
readme = "README.md"
packages = [{include = "test_runner"}]

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.65.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
